using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class SliderSyncModel {
    //[RealtimeProperty(1, true, true)]
    //private float _slidevalue;

    [RealtimeProperty(1, true, true)]
    private float _slidevalue;
}
/* ----- Begin Normal Autogenerated Code ----- */
public partial class SliderSyncModel : IModel {
    // Properties
    public float slidevalue {
        get { return _cache.LookForValueInCache(_slidevalue, entry => entry.slidevalueSet, entry => entry.slidevalue); }
        set { if (value == slidevalue) return; _cache.UpdateLocalCache(entry => { entry.slidevalueSet = true; entry.slidevalue = value; return entry; }); FireSlidevalueDidChange(value); }
    }
    
    // Events
    public delegate void SlidevalueDidChange(SliderSyncModel model, float value);
    public event         SlidevalueDidChange slidevalueDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool  slidevalueSet;
        public float slidevalue;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public SliderSyncModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireSlidevalueDidChange(float value) {
        try {
            if (slidevalueDidChange != null)
                slidevalueDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        Slidevalue = 1,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _slidevalue = slidevalue;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteFloatLength((uint)PropertyID.Slidevalue);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.slidevalueSet)
                    length += WriteStream.WriteFloatLength((uint)PropertyID.Slidevalue);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteFloat((uint)PropertyID.Slidevalue, _slidevalue);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.slidevalueSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.slidevalueSet)
                    stream.WriteFloat((uint)PropertyID.Slidevalue, entry.slidevalue);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool slidevalueExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.slidevalueSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Slidevalue: {
                    float previousValue = _slidevalue;
                    
                    _slidevalue = stream.ReadFloat();
                    
                    if (!slidevalueExistsInChangeCache && _slidevalue != previousValue)
                        FireSlidevalueDidChange(_slidevalue);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
